# ============================================================================
# Market Research MVP - One-Click Local Setup Script
# ============================================================================
# This script automates the complete local setup for the Market Research MVP
# No manual steps required - just run it and everything is ready!
# ============================================================================

# Color definitions for output
$colors = @{
    Success = 'Green'
    Error = 'Red'
    Warning = 'Yellow'
    Info = 'Cyan'
    Step = 'Magenta'
}

# Utility function for colored output
function Write-Status {
    param(
        [string]$Message,
        [ValidateSet('Success', 'Error', 'Warning', 'Info', 'Step')]
        [string]$Type = 'Info'
    )
    Write-Host "[$Type] $Message" -ForegroundColor $colors[$Type]
}

# Banner
Write-Host "`n" -NoNewline
Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║    Market Research MVP - One-Click Local Setup Script          ║" -ForegroundColor Cyan
Write-Host "║                       v1.0                                    ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Get script location (where setup.ps1 is running from)
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$backendDir = Join-Path $projectRoot "backend"
$frontendDir = Join-Path $projectRoot "frontend"
$databaseDir = Join-Path $projectRoot "database"

Write-Status "Project Root: $projectRoot" "Info"
Write-Status "Backend Dir: $backendDir" "Info"
Write-Status "Frontend Dir: $frontendDir" "Info"

# ============================================================================
# STEP 1: Check Prerequisites
# ============================================================================
Write-Status "STEP 1: Checking prerequisites..." "Step"

# Check Python
Write-Host "  → Checking Python..."
$pythonCheck = python --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ Python installed: $pythonCheck" "Success"
} else {
    Write-Status "  ✗ Python not found. Please install Python 3.8+ from https://www.python.org" "Error"
    exit 1
}

# Check Node.js
Write-Host "  → Checking Node.js..."
$nodeCheck = node --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ Node.js installed: $nodeCheck" "Success"
} else {
    Write-Status "  ✗ Node.js not found. Please install Node.js from https://nodejs.org" "Error"
    exit 1
}

# Check npm
Write-Host "  → Checking npm..."
$npmCheck = npm --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ npm installed: $npmCheck" "Success"
} else {
    Write-Status "  ✗ npm not found. Please install Node.js (includes npm)" "Error"
    exit 1
}

# Check Git
Write-Host "  → Checking Git..."
$gitCheck = git --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ Git installed: $gitCheck" "Success"
} else {
    Write-Status "  ⚠ Git not found (optional, but recommended)" "Warning"
}

Write-Host ""

# ============================================================================
# STEP 2: Create Database Directory
# ============================================================================
Write-Status "STEP 2: Creating database directory structure..." "Step"

if (-not (Test-Path $databaseDir)) {
    New-Item -ItemType Directory -Path $databaseDir | Out-Null
    Write-Status "  ✓ Database directory created" "Success"
} else {
    Write-Status "  ✓ Database directory already exists" "Success"
}

Write-Host ""

# ============================================================================
# STEP 3: Create Backend .env File
# ============================================================================
Write-Status "STEP 3: Creating backend/.env file..." "Step"

$backendEnvPath = Join-Path $backendDir ".env"

if (Test-Path $backendEnvPath) {
    Write-Status "  ⚠ .env file already exists at $backendEnvPath" "Warning"
    Write-Host "  → Backing up existing .env to .env.backup"
    Copy-Item $backendEnvPath "$backendEnvPath.backup" -Force
} else {
    Write-Status "  → Creating new .env file" "Info"
}

$backendEnvContent = @"
# Backend Environment Variables
# Generated by setup.ps1 - Local Development

# Database Configuration
DATABASE_URL=sqlite:///./test.db

# Supabase (Local Dummy Values)
SUPABASE_URL=http://localhost:5432
SUPABASE_KEY=dummy_test_key_local_dev_only

# Stripe (Test Keys - Local Development Only)
STRIPE_SECRET_KEY=sk_test_dummy123456789abcdefghijklmnop
STRIPE_WEBHOOK_SECRET=whsec_test_dummy123456789abcdefghijklmnop

# Anthropic API (Local Dummy - Replace with real key in production)
ANTHROPIC_API_KEY=sk_test_dummy123456789abcdefghijklmnop

# CORS Configuration
CORS_ORIGINS=http://localhost:3000

# Debug Mode (Set to False in production)
DEBUG=True

# Server Configuration
SERVER_HOST=localhost
SERVER_PORT=8000

# Session Configuration
SECRET_KEY=dev_secret_key_change_in_production_$(Get-Random)
"@

Set-Content -Path $backendEnvPath -Value $backendEnvContent -Force
Write-Status "  ✓ Backend .env created successfully" "Success"
Write-Host ""

# ============================================================================
# STEP 4: Create Frontend .env.local File
# ============================================================================
Write-Status "STEP 4: Creating frontend/.env.local file..." "Step"

$frontendEnvPath = Join-Path $frontendDir ".env.local"

if (Test-Path $frontendEnvPath) {
    Write-Status "  ⚠ .env.local file already exists" "Warning"
    Write-Host "  → Backing up existing .env.local to .env.local.backup"
    Copy-Item $frontendEnvPath "$frontendEnvPath.backup" -Force
} else {
    Write-Status "  → Creating new .env.local file" "Info"
}

$frontendEnvContent = @"
# Frontend Environment Variables
# Generated by setup.ps1 - Local Development

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:8000

# Stripe (Test Keys - Local Development Only)
NEXT_PUBLIC_STRIPE_KEY=pk_test_dummy123456789abcdefghijklmnop

# Supabase (Local Dummy Values)
NEXT_PUBLIC_SUPABASE_URL=http://localhost:5432
NEXT_PUBLIC_SUPABASE_KEY=dummy_test_key_local_dev_only

# Application Environment
NEXT_PUBLIC_ENV=development

# Debug Mode
NEXT_PUBLIC_DEBUG=true
"@

Set-Content -Path $frontendEnvPath -Value $frontendEnvContent -Force
Write-Status "  ✓ Frontend .env.local created successfully" "Success"
Write-Host ""

# ============================================================================
# STEP 5: Install Backend Dependencies
# ============================================================================
Write-Status "STEP 5: Installing backend dependencies..." "Step"

Push-Location $backendDir
Write-Status "  → Running: pip install -r requirements.txt" "Info"
pip install -r requirements.txt --quiet
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ Backend dependencies installed successfully" "Success"
} else {
    Write-Status "  ✗ Failed to install backend dependencies" "Error"
    Pop-Location
    exit 1
}
Pop-Location
Write-Host ""

# ============================================================================
# STEP 6: Install Frontend Dependencies
# ============================================================================
Write-Status "STEP 6: Installing frontend dependencies..." "Step"

Push-Location $frontendDir
Write-Status "  → Running: npm install" "Info"
npm install
if ($LASTEXITCODE -eq 0) {
    Write-Status "  ✓ Frontend dependencies installed successfully" "Success"
} else {
    Write-Status "  ✗ Failed to install frontend dependencies" "Error"
    Pop-Location
    exit 1
}
Pop-Location
Write-Host ""

# ============================================================================
# STEP 7: Initialize SQLite Database
# ============================================================================
Write-Status "STEP 7: Initializing SQLite database..." "Step"

$dbPath = Join-Path $projectRoot "test.db"

if (Test-Path $dbPath) {
    Write-Status "  ⚠ Database file already exists: $dbPath" "Warning"
    $response = Read-Host "  → Reinitialize database? (y/n)"
    if ($response -eq 'y' -or $response -eq 'Y') {
        Remove-Item $dbPath -Force
        Write-Status "  → Deleted existing database" "Info"
    } else {
        Write-Status "  → Keeping existing database" "Info"
        Write-Host ""
        Write-Host "Skipping database initialization..."
        goto DatabaseComplete
    }
}

try {
    # Create database file and initialize schema
    Write-Status "  → Initializing SQLite database with schema..." "Info"
    
    Push-Location $backendDir
    
    # Run Flask database initialization (if the app supports it)
    # This is a safe way to initialize without manual SQL
    python -c "
from app import app, db
with app.app_context():
    db.create_all()
    print('Database initialized successfully')
" 2>&1 | ForEach-Object { Write-Status "    $($_)" "Info" }
    
    Pop-Location
    
    if (Test-Path $dbPath) {
        Write-Status "  ✓ SQLite database initialized at: $dbPath" "Success"
    } else {
        Write-Status "  ⚠ Database not created by Flask (may initialize on first run)" "Warning"
    }
} catch {
    Write-Status "  ⚠ Could not auto-initialize database - it will be created on first run" "Warning"
}

:DatabaseComplete
Write-Host ""

# ============================================================================
# STEP 8: Success Banner
# ============================================================================
Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                    ✓ SETUP COMPLETE!                          ║" -ForegroundColor Green
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

# ============================================================================
# STEP 9: Display Next Steps
# ============================================================================
Write-Status "NEXT STEPS - Start the Application:" "Step"
Write-Host ""
Write-Host "  Option A: Run servers in background (recommended)" -ForegroundColor Cyan
Write-Host "  ────────────────────────────────────────────────"
Write-Host ""
Write-Host "  1. Open Terminal 1 (Backend):"
Write-Host "     cd $backendDir"
Write-Host "     python app.py"
Write-Host ""
Write-Host "  2. Open Terminal 2 (Frontend):"
Write-Host "     cd $frontendDir"
Write-Host "     npm run dev"
Write-Host ""
Write-Host "  Then visit:"
Write-Host "     Backend API:  http://localhost:8000" -ForegroundColor Yellow
Write-Host "     Frontend App: http://localhost:3000" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Option B: Launch both servers automatically (below)" -ForegroundColor Cyan
Write-Host "  ─────────────────────────────────────────────────"
Write-Host ""

# ============================================================================
# STEP 10: Optional Auto-Launch
# ============================================================================
$launchServers = Read-Host "Launch both servers now? (y/n)"

if ($launchServers -eq 'y' -or $launchServers -eq 'Y') {
    Write-Host ""
    Write-Status "Launching Backend Server..." "Step"
    Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location '$backendDir'; python app.py"
    Start-Sleep -Seconds 2
    
    Write-Status "Launching Frontend Server..." "Step"
    Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location '$frontendDir'; npm run dev"
    Start-Sleep -Seconds 2
    
    Write-Host ""
    Write-Status "✓ Both servers launched in separate windows!" "Success"
    Write-Host ""
    Write-Host "  Backend will start on:   http://localhost:8000" -ForegroundColor Yellow
    Write-Host "  Frontend will start on:  http://localhost:3000" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  The frontend will open in your browser automatically." -ForegroundColor Cyan
    Write-Host "  Give it 10-15 seconds to fully load." -ForegroundColor Cyan
    Write-Host ""
} else {
    Write-Host ""
    Write-Status "Setup complete! Follow the steps above to start your servers." "Success"
    Write-Host ""
}

# ============================================================================
# Final Notes
# ============================================================================
Write-Host "═════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "📝 IMPORTANT NOTES:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Environment Variables:" -ForegroundColor White
Write-Host "   - Backend .env:  $backendEnvPath" -ForegroundColor Gray
Write-Host "   - Frontend .env: $frontendEnvPath" -ForegroundColor Gray
Write-Host "   - These contain DUMMY values for local development" -ForegroundColor Gray
Write-Host "   - Replace with real keys before deploying to production!" -ForegroundColor Red
Write-Host ""
Write-Host "2. Database:" -ForegroundColor White
Write-Host "   - SQLite database: $dbPath" -ForegroundColor Gray
Write-Host "   - Data is stored locally (safe for development)" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Port Information:" -ForegroundColor White
Write-Host "   - Backend:  Port 8000 (http://localhost:8000)" -ForegroundColor Gray
Write-Host "   - Frontend: Port 3000 (http://localhost:3000)" -ForegroundColor Gray
Write-Host "   - Make sure these ports are not in use!" -ForegroundColor Gray
Write-Host ""
Write-Host "4. Troubleshooting:" -ForegroundColor White
Write-Host "   - If servers don't start, check the terminal windows" -ForegroundColor Gray
Write-Host "   - Make sure Python/Node packages are installed" -ForegroundColor Gray
Write-Host "   - Check that no other apps use ports 3000 or 8000" -ForegroundColor Gray
Write-Host ""
Write-Host "═════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

Read-Host "Press Enter to close this window"
